config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :entries, only: [:index, :create, :update, :destroy] do
    collection do
      post :update_all
      delete :destroy_all
    end
  end
  resources :invoices, only: [:index, :show, :create, :edit, :update, :destroy]
  resources :projects, only: [:index, :create, :edit, :update, :destroy] do
    member do
      post :import
      put :upload
    end
  end

  root to: "entries#index"
end

app/models/entry.rb
class Entry < ApplicationRecord
  self.inheritance_column = nil
  paginates_per 20

  enum type: {development: 1, maintenance: 2}
  belongs_to :invoice, optional: true
  belongs_to :project
  belongs_to :user

  validates :external_id, presence: true, uniqueness: {scope: :user_id}
  validates :exact, inclusion: {in: [true, false]}
  validates :description, presence: true
  validates :hours, presence: true, inclusion: {in: (0...24).step(0.5).to_a}
  validates :ended_at, presence: true
  validates :type, presence: true

  before_validation :assign_day, :assign_external_id
  before_save :assign_invoice

  def self.unassigned
    where(invoice_id: nil)
  end

  def previous
    self.class.where("ended_at < ?", ended_at).order(ended_at: :asc).last
  end

  private

  def assign_day
    self.day = ended_at&.in_time_zone&.to_date
  end

  def assign_external_id
    self.external_id ||= (DateTime.now.to_f * 1000 * 1000).to_i
  end

  def assign_invoice
    self.invoice = user.invoices.including_day(ended_at).first
  end
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  before_action :assign_user, :assign_projects, :assign_invoices
  before_action :assign_entries, only: [:index, :update_all, :destroy_all]

  def index
    @entry = @user.entries.build
    @update_entries_form = UpdateEntriesForm.new(entries: @entries)
    invoice_ids = @entries.distinct.except(:limit, :offset, :order).pluck(:invoice_id)
    @invoice = Invoice.find_by(id: invoice_ids.first) if invoice_ids.size == 1
  end

  def create
    @entry = @user.entries.create(entry_params)
  end

  def update
    @entry = @user.entries.find(params[:id])
    @entry.update(entry_params)
  end

  def update_all
    @update_entries_form = UpdateEntriesForm.new(update_entries_form_params)
    @update_entries_form.entries = @entries
    if @update_entries_form.valid?
      @update_entries_form.update_all
      redirect_to entries_path(q: params.fetch(:q, {}).to_unsafe_hash)
    end
  end

  def destroy_all
    @entries.destroy_all
    redirect_to entries_path(q: params.fetch(:q, {}).to_unsafe_hash)
  end

  def destroy
    @entry = @user.entries.find(params[:id])
    @entry.destroy
  end

  private

  def assign_user
    @user = current_user
  end

  def assign_projects
    @projects = @user.projects
  end

  def assign_invoices
    @invoices = @user.invoices
  end

  def assign_entries
    @q = @user.entries.ransack(params[:q])
    @entries =
      @q.result
        .includes(:invoice, :project)
        .page(params[:page])
        .order(:ended_at, :id)
  end

  def entry_params
    params.require(:entry).permit(:description, :type, :hours, :ended_at, :project_id, :exact)
  end

  def update_entries_form_params
    params.require(:update_entries_form).permit(:hours, :description, :type)
  end
end

app/views/entries/_entry.html.erb
<tr id="entry_<%= entry.id %>">
  <td>
    <%= link_to entry.day, entries_path(q: {day_eq: entry.day}) %>
    <span class="hover-only"><%= octicon "search" %></span>
  </td>
  <td>
    <%= link_to truncate(entry.description, length: 50), "javascript:void(0)", data: {toggle: "modal", target: "#edit_entry_#{entry.id}"} %>
    <span class="hover-only"><%= octicon "pencil" %></span>
  </td>
  <td class="text-center">
    <%= link_to entry.project.name, entries_path(q: {project_id_eq: entry.project_id}) %>
    <span class="hover-only"><%= octicon "search" %></span>
  </td>
  <td class="text-center">
    <% if entry.invoice %>
      <%= link_to entry.invoice.number, entries_path(q: {invoice_id_eq: entry.invoice_id}) %>
      <span class="hover-only"><%= octicon "search" %></span>
    <% else %>
      <small class='text-muted'>nieprzypisany</small>
      <span class="invisible"><%= octicon "search" %></span>
    <% end %>
  </td>
  <td class="text-center">
    <% if entry.development? %>
      <%= link_to "programowanie", entry_path(entry), class: "badge badge-success", data: {method: :patch, remote: true, params: "entry[type]=maintenance"} %>
    <% end %>
    <% if entry.maintenance? %>
      <%= link_to "utrzymanie", entry_path(entry), class: "badge badge-secondary", data: {method: :patch, remote: true, params: "entry[type]=development"} %>
    <% end %>
    <span class="hover-only"><%= octicon "pencil" %></span>
  </td>
  <td class="text-right">
    <%= link_to entry.hours, "javascript:void(0)", data: {toggle: "modal", target: "#edit_entry_#{entry.id}"} %>
    <span class="hover-only"><%= octicon "pencil" %></span>
  </td>
</tr>

app/views/entries/_form.html.erb
<%= form_for entry, html: {class: "modal", tabindex: -1, role: "dialog"}, data: {remote: true} do |form| %>
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">
          <% if entry.new_record? %>
            Nowy wpis
          <% else %>
            Edytuj wpis
          <% end %>
        </h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true"><%= octicon "x" %></span>
        </button>
      </div>
      <div class="modal-body">
        <%= form.hidden_field :exact, value: "1" %>

        <% if entry.new_record? %>
          <div class="form-group">
            <%= form.label :ended_at, class: "form-label" %>
            <%= form.date_field :ended_at, class: "form-control", autocomplete: "off" %>
            <%= bootstrap_invalid_feedback_for(form.object, :ended_at) %>
          </div>
        <% end %>

        <div class="form-group">
          <%= form.label :description, class: "form-label" %>
          <%= form.text_area :description, class: "form-control", autocomplete: "off" %>
          <%= bootstrap_invalid_feedback_for(form.object, :description) %>
        </div>

        <div class="form-group">
          <%= form.label :hours, class: "form-label" %>
          <%= form.number_field :hours, class: "form-control", step: 0.5, min: 0, autocomplete: "off" %>
          <%= bootstrap_invalid_feedback_for(form.object, :hours) %>
        </div>

        <div class="form-group">
          <%= form.label :project_id, class: "form-label" %>
          <%= form.collection_select :project_id, @projects, :id, :name, {prompt: true}, class: "form-control custom-select", autocomplete: "off" %>
          <%= bootstrap_invalid_feedback_for(form.object, :project) %>
        </div>

        <div class="form-group">
          <%= form.label :type, class: "form-label" %>
          <div class="form-check">
            <%= form.radio_button :type, "development", class: "form-check-input" %>
            <%= form.label :type_development, class: "form-check-label" do %>
              <span class="badge badge-success">programowanie</span>
            <% end %>
          </div>
          <div class="form-check">
            <%= form.radio_button :type, "maintenance", class: "form-check-input" %>
            <%= form.label :type_maintenance, class: "form-check-label" do %>
              <span class="badge badge-secondary">utrzymanie</span>
            <% end %>
          </div>
          <%= bootstrap_invalid_feedback_for(form.object, :type) %>
        </div>
      </div>
      <div class="modal-footer">
        <%= link_to "Usuń", entry_path(form.object), class: "btn btn-danger", data: {method: :delete, confirm: "Czy na pewno usunąć ten wpis?", remote: true} if form.object.persisted? %>
        <%= form.submit "Zapisz", class: "btn btn-primary" %>
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Anuluj</button>
      </div>
    </div>
  </div>
<% end %>

app/views/entries/_table.html.erb
<%= render partial: "entries/form", collection: @entries, as: :entry %>

<table class="table table-hover table-sm" id="entries">
  <thead>
    <tr>
      <th>
        Data
        <span class="hover-only"><%= octicon "pencil" %></span>
      </th>
      <th>
        Opis
        <span class="hover-only"><%= octicon "pencil" %></span>
      </th>
      <th class="text-center">
        Projekt
        <span class="hover-only"><%= octicon "pencil" %></span>
      </th>
      <th class="text-center">
        Faktura
        <span class="hover-only"><%= octicon "pencil" %></span>
      </th>
      <th class="text-center">
        Typ
        <span class="hover-only"><%= octicon "pencil" %></span>
      </th>
      <th class="text-right">
        Liczba godzin
        <span class="hover-only"><%= octicon "pencil" %></span>
      </th>
    </tr>
  </thead>
  <% if @entries.count > 0 %>
    <tbody>
      <%= render @entries %>
    </tbody>
  <% else %>
    <tr>
      <td colspan="6" class="text-center text-muted">Nie masz żadnych wpisów</td>
    </tr>
  <% end %>
  <tfoot>
    <tr>
      <th colspan="5" class="text-right">
        Suma
      </th>
      <td class="text-right">
        <%= @entries.except(:limit, :offset).sum(:hours) %>
        <span class="hover-only"><%= octicon "pencil" %></span>
      </td>
    </tr>
  </tfoot>
</table>

app/views/entries/_update_entries_form.html.erb
<%= form_for update_entries_form, url: update_all_entries_path(q: params.fetch(:q, {}).to_unsafe_h), html: {class: "modal", tabindex: -1, role: "dialog"}, data: {remote: true} do |form| %>
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">
          Zmień <%= t("entry_count", count: @entries.total_count) %>
        </h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true"><%= octicon "x" %></span>
        </button>
      </div>
      <div class="modal-body">
        <div class="form-group">
          <%= form.label :description, class: "form-label" %>
          <%= form.text_field :description, class: "form-control", placeholder: "Bez zmian" %>
          <%= bootstrap_invalid_feedback_for(form.object, :description) %>
        </div>

        <div class="form-group">
          <%= form.label :hours, class: "form-label" %>
          <%= form.number_field :hours, class: "form-control", step: 0.5, min: 0, placeholder: "Bez zmian" %>
          <%= bootstrap_invalid_feedback_for(form.object, :hours) %>
        </div>

        <div class="form-group">
          <%= form.label :type, class: "form-label" %>
          <div class="form-check">
            <%= form.radio_button :type, "", class: "form-check-input", checked: form.object.type.blank? %>
            <%= form.label :type_, class: "form-check-label" do %>
              bez zmian
            <% end %>
          </div>
          <div class="form-check">
            <%= form.radio_button :type, "development", class: "form-check-input" %>
            <%= form.label :type_development, class: "form-check-label" do %>
              <span class="badge badge-success">programowanie</span>
            <% end %>
          </div>
          <div class="form-check">
            <%= form.radio_button :type, "maintenance", class: "form-check-input" %>
            <%= form.label :type_maintenance, class: "form-check-label" do %>
              <span class="badge badge-secondary">utrzymanie</span>
            <% end %>
          </div>
          <%= bootstrap_invalid_feedback_for(form.object, :project_id) %>
        </div>
      </div>
      <div class="modal-footer">
        <%= link_to "Usuń", destroy_all_entries_path(q: params.fetch(:q, {}).to_unsafe_hash), class: "btn btn-danger", data: {method: :delete, confirm: "Czy na pewno usunąć #{form.object.entries_count} wpisów?", remote: true} %>
        <%= form.submit "Zmień", class: "btn btn-primary", data: {confirm: "Zmienione zostanie #{form.object.entries_count} wpisów. Kontynuować?"} %>
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Anuluj</button>
      </div>
    </div>
  </div>
<% end %>

app/views/entries/create.js.erb
(function () {
  var form = document.getElementById("new_entry");

  <% if @entry.valid? %>
    jQuery(form).modal("hide");
    Turbolinks.clearCache();
    Turbolinks.visit(window.location);
  <% else %>
    form.innerHTML = "<%= j render('form', entry: @entry) %>";
  <% end %>
})();

app/views/entries/destroy.js.erb
(function () {
  var entryNode = document.getElementById("entry_<%= @entry.id %>");
  var form = document.getElementById("edit_entry_<%= @entry.id %>");

  if (entryNode) {
    entryNode.parentNode.removeChild(entryNode);
  } else {
    Turbolinks.clearCache();
    Turbolinks.visit(window.location);
  }

  jQuery(form).modal("hide");
})()

app/views/entries/index.html.erb
<% if @invoice.present? %>
  <% invoiced_hours = @invoice.hours %>
  <% logged_hours = @invoice.entries.sum(:hours) %>

  <div class="alert <%= "alert-success" if invoiced_hours == logged_hours %> <%= "alert-warning" if invoiced_hours > logged_hours %> <%= "alert-danger" if invoiced_hours < logged_hours %>" role="alert">
    Faktura <%= @invoice.number %> -  zafakturowano: <%= invoiced_hours %>h, zalogowano: <%= logged_hours %>h
  </div>
<% end %>

<div class="my-3">
  <%= search_form_for @q, url: entries_path, method: :get, remote: true do |form| %>
    <div class="d-flex flex-row">
      <div class="flex-fill mr-1">
        <%= form.search_field :description_cont, class: "form-control form-control-sm", placeholder: "Opis", autocomplete: "off" %>
      </div>
      <div class="mr-1">
        <div class="input-group mb-3">
          <div class="input-group-prepend">
            <%= link_to entries_path(q: params.fetch(:q, {}).to_unsafe_h.merge(day_eq: form.object.day_eq&.advance(days: -1))), class: "btn btn-sm btn-secondary #{'disabled' if form.object.day_eq.blank?}" do %>
              <i class="fa fa-chevron-left"></i>
            <% end %>
          </div>
          <%= form.date_field :day_eq, class: "form-control form-control-sm", autocomplete: "off", value: form.object.day_eq %>
          <div class="input-group-append">
            <%= link_to entries_path(q: params.fetch(:q, {}).to_unsafe_h.merge(day_eq: form.object.day_eq&.advance(days: 1))), class: "btn btn-sm btn-secondary #{'disabled' if form.object.day_eq.blank?}" do %>
              <i class="fa fa-chevron-right"></i>
            <% end %>
          </div>
        </div>
      </div>
      <div class="mr-1">
        <%= form.collection_select :project_id_eq, @projects, :id, :name, {include_blank: "Dowolny projekt"}, class: "form-control form-control-sm", autocomplete: "off", oninput: "Rails.fire(this.form, 'submit')" %>
      </div>
      <div class="mr-1">
        <%= form.collection_select :invoice_id_eq, @invoices, :id, :number, {include_blank: "Dowolna faktura"}, class: "form-control form-control-sm", autocomplete: "off", oninput: "Rails.fire(this.form, 'submit')" %>
      </div>
      <div class="mr-1">
        <%= form.submit "Filtruj", class: "btn btn-primary btn-sm btn-block" %>
      </div>
      <div class="">
        <%= link_to entries_path, type: "button", class: "btn btn-secondary btn-sm btn-block", data: {remote: true} do %>
          <i class="fa fa-times"></i>
        <% end %>
      </div>
    </div>
  <% end %>
</div>

<%= render "form", entry: @entry %>
<%= render "update_entries_form", update_entries_form: @update_entries_form %>
<%= render "table" %>

<div class="d-flex justify-content-between">
  <div>
    <%= paginate @entries %>
  </div>
  <div class="text-right">
    <%= link_to "javascript:void(0)", type: "button", class: "btn btn-warning", data: {toggle: "modal", target: "#new_update_entries_form"} do %>
      Zmień <%= t("entry_count", count: @entries.total_count) %>
    <% end %>
    <%= link_to "Dodaj nowy wpis", "javascript:void(0)", type: "button", class: "btn btn-success", data: {toggle: "modal", target: "#new_entry"} %>
  </div>
</div>

app/views/entries/index.js.erb
Turbolinks.clearCache();
Turbolinks.visit("<%= url_for(params.to_unsafe_h).html_safe %>");

app/views/entries/update.js.erb
(function () {
  var form = document.getElementById("edit_entry_<%= @entry.id %>");

  <% if @entry.valid? %>
    Turbolinks.clearCache();
    Turbolinks.visit(window.location);
  <% else %>
    if (form) {
      form.innerHTML = "<%= j render('form', entry: @entry) %>";
    }
  <% end %>
})();

app/views/entries/update_all.js.erb
document.getElementById("new_update_entries_form").innerHTML = "<%= j render('update_entries_form', update_entries_form: @update_entries_form) %>";