config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :entries, only: [:index, :create, :update, :destroy] do
    collection do
      post :update_all
      delete :destroy_all
    end
  end
  resources :invoices, only: [:index, :show, :create, :edit, :update, :destroy]
  resources :projects, only: [:index, :create, :edit, :update, :destroy] do
    member do
      post :import
      put :upload
    end
  end

  root to: "entries#index"
end

app/models/invoice.rb
class Invoice < ApplicationRecord
  has_many :entries, dependent: :nullify
  belongs_to :user

  validates :number, presence: true
  validates :from, presence: true
  validates :to, presence: true
  validates :hours, presence: true

  after_save :associate_entries

  def self.including_day(day)
    where("invoices.from <= ?", day.to_date).where("? <= invoices.to", day.to_date)
  end

  def period
    (from..to)
  end

  def development_ratio
    entries.development.sum(:hours) / reported_hours
  end

  def maintenance_ratio
    entries.maintenance.sum(:hours) / reported_hours
  end

  def reported_hours
    entries.sum(:hours)
  end

  private

  def associate_entries
    user.entries.where(day: period).update_all(invoice_id: id)
  end
end

app/controllers/invoices_controller.rb
class InvoicesController < ApplicationController
  before_action :assign_user, :assign_invoices, :assign_invoice

  def index
    @invoices = @user.invoices.order(from: :asc)
  end

  def show
    @invoice = @user.invoices.find(params[:id])
    @projects = @user.projects
    @entries_by_day = @invoice.entries.order(:ended_at, :id).group_by(&:day)
  end

  def create
    @invoice = @user.invoices.build(invoice_params)
    if @invoice.save
      redirect_to invoices_path
    end
  end

  def update
    @invoice = @user.invoices.find(params[:id])
    if @invoice.update(invoice_params)
      redirect_to invoices_path
    end
  end

  def destroy
    @invoice = @user.invoices.find(params[:id])
    @invoice.destroy
    redirect_to invoices_path
  end

  private

  def assign_user
    @user = current_user
  end

  def assign_invoices
    @invoices = @user.invoices
  end

  def assign_invoice
    @invoice = @user.invoices.build
    last_invoice = @user.invoices.order(to: :asc).last
    @invoice.from = last_invoice&.to&.advance(days: 1) || "#{Date.current.year}-01-01".to_date
    @invoice.to = @invoice.from.end_of_month
  end

  def invoice_params
    params.require(:invoice).permit(:number, :from, :to, :hours)
  end
end

app/helpers/invoice_helper.rb
module InvoiceHelper
  def invoice_row_classes(invoice)
    "".tap do |classes|
      classes << 'table-danger' if invoice.entries.sum(:hours) > invoice.hours
      classes << 'table-warning' if invoice.entries.sum(:hours) < invoice.hours
      classes << 'table-success' if invoice.entries.sum(:hours) == invoice.hours
    end
  end
end

app/views/invoices/_form.html.erb
<%= form_for invoice, html: {class: "modal", tabindex: -1, role: "dialog"}, data: {remote: true} do |form| %>
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">
          <% if form.object.new_record? %>
            Nowa faktura
          <% else %>
            Edytuj fakturę
          <% end %>
        </h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true"><%= octicon "x" %></span>
        </button>
      </div>
      <div class="modal-body">
        <div class="form-group">
          <%= form.label :number, class: "form-label" %>
          <%= form.text_field :number, class: "form-control", autocomplete: "off" %>
          <%= bootstrap_invalid_feedback_for(form.object, :number) %>
        </div>

        <div class="form-group">
          <%= form.label :from, class: "form-label" %>
          <%= form.date_field :from, class: "form-control", autocomplete: "off" %>
          <%= bootstrap_invalid_feedback_for(form.object, :from) %>
        </div>

        <div class="form-group">
          <%= form.label :to, class: "form-label" %>
          <%= form.date_field :to, class: "form-control", autocomplete: "off" %>
          <%= bootstrap_invalid_feedback_for(form.object, :to) %>
        </div>

        <div class="form-group">
          <%= form.label :hours, class: "form-label" %>
          <%= form.number_field :hours, class: "form-control", step: 0.5, min: 0, autocomplete: "off" %>
          <%= bootstrap_invalid_feedback_for(form.object, :hours) %>
        </div>
      </div>
      <div class="modal-footer">
        <%= link_to "Usuń", invoice_path(form.object), class: "btn btn-danger", data: {method: :delete, confirm: "Czy na pewno usunąć tę fakturę?", remote: true} if form.object.persisted? %>
        <%= form.submit "Zapisz", class: "btn btn-primary" %>
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Anuluj</button>
      </div>
    </div>
  </div>
<% end %>

app/views/invoices/_invoice.html.erb
<tr id="invoice-<%= invoice.id %>" class="<%= invoice_row_classes(invoice) %>">
  <td>
    <%= link_to invoice.number, "javascript:void(0)", data: {toggle: "modal", target: "#edit_invoice_#{invoice.id}"} %>
  </td>
  <td class="text-center">
    <%= invoice.from %> &mdash; <%= invoice.to %>
  </td>
  <td class="text-right">
    <%= invoice.hours %>
  </td>
  <td class="text-right">
    <%= invoice.entries.sum(:hours) %>
  </td>
  <td class="text-right">
    <%= number_to_percentage(invoice.development_ratio * 100, precision: 0) %>
  </td>
  <td class="text-right">
    <%= link_to "Ewidencja", invoice_path(invoice), class: "btn btn-sm btn-info" %>
  </td>
</tr>

app/views/invoices/_table.html.erb
<%= render partial: "invoices/form", collection: @invoices, as: :invoice %>

<table class="table table-sm" id="invoices">
  <thead>
    <tr>
      <th class="">Numer</th>
      <th class="text-center">Okres</th>
      <th class="text-right">Liczba zafakturowanych godzin</th>
      <th class="text-right">Liczba zalogowanych godzin</th>
      <th class="text-right">Procent programowania</th>
      <th class="text-right"></th>
    </tr>
  </thead>
  <% if @invoices.count > 0 %>
    <tbody>
      <%= render @invoices %>
    </tbody>
    <tfoot>
      <tr>
        <th colspan="2" class="text-right">
          Suma
        </th>
        <th class="text-right">
          <%= current_user.invoices.sum(:hours) %>
        </th>
        <th class="text-right">
          <%= current_user.invoices.joins(:entries).sum("entries.hours") %>
        </th>
        <th class="text-right">
          <%= number_to_percentage(@invoices.map(&:development_ratio).sum / @invoices.size * 100, precision: 0)  %>
        </th>
      </tr>
    </tfoot>
  <% else %>
    <tr>
      <td colspan="5" class="text-center text-muted">Nie masz żadnych faktur</td>
    </tr>
  <% end %>
</table>

app/views/invoices/create.js.erb
document.getElementById("new_invoice").innerHTML = "<%= j render('form', invoice: @invoice) %>";

app/views/invoices/index.html.erb
<%= render "table" %>

<div class="text-right">
  <%= link_to "Dodaj fakturę", "javascript:void(0)", class: "btn btn-success", data: {toggle: "modal", target: "#new_invoice"} %>
</div>

<%= render "form", invoice: @invoice %>

app/views/invoices/new.html.erb
<div class="row my-3">
  <div class="col">
    <h2>
      Nowa faktura
    </h2>
  </div>
</div>

<%= render "form", invoice: @invoice %>

app/views/invoices/show.html.erb
<div class="row my-3">
  <div class="col">
    <h2>
      Faktura <%= @invoice.number %>
    </h2>
  </div>
  <div class="col d-print-none text-right">
    <%= link_to "Eksportuj do CSV", invoice_path(format: :csv), class: "btn btn-info" %>
    <a href="javascript:window.print()" class="btn btn-info">Drukuj ewidencję</a>
  </div>
</div>

<table class="table table-hover" id="entries">
  <thead>
    <tr>
      <th class="text-center">
        Data
      </th>
      <th class="text-center">
        Opis
      </th>
      <th class="text-center">
        Typ
      </th>
      <th class="text-right">
        Liczba godzin
      </th>
    </tr>
  </thead>
  <tbody>
    <% @entries_by_day.each do |day, entries| %>
      <% if entries.present? %>
        <% entries.each.with_index do |entry, i| %>
          <tr>
            <% if i.zero? %>
              <td rowspan="<%= entries.size %>" class="text-center align-middle">
                <div>
                  <%= l day, format: "%A, %-d %B %Y" %>
                </div>
              </td>
            <% end %>
            <td>
              <%= render "entries/form", entry: entry %>
              <%= link_to entry.description, "javascript:void(0)", data: {toggle: "modal", target: "#edit_entry_#{entry.id}"}, class: "d-print-none" %>
              <span class="d-none d-print-block"><%= entry.description %></span>
            </td>
            <td class="text-center">
              <% if entry.development? %>
                programowanie
              <% end %>
              <% if entry.maintenance? %>
                utrzymanie
              <% end %>
            </td>
            <td class="text-right">
              <%= entry.hours %>
            </td>
          </tr>
        <% end %>
      <% end %>
    <% end %>
  </tbody>
  <tr>
    <th rowspan="6" class="align-middle text-center">
      Podsumowanie
    </th>
    <th class="text-right" colspan="2">
      Liczba zafakturowanych godzin
    </th>
    <td class="text-right">
      <%= @invoice.hours %>
    </td>
  </tr>
  <tr>
    <th class="text-right" colspan="2">
      Liczba zaraportowanych godzin
    </th>
    <td class="text-right">
      <%= @invoice.entries.sum(:hours) %>
    </td>
  </tr>
  <tr>
    <th class="text-right" colspan="2">
      Liczba zaraportowanych godzin programowania
    </th>
    <td class="text-right">
      <%= @invoice.entries.development.sum(:hours) %>
    </td>
  </tr>
  <tr>
    <th class="text-right" colspan="2">
      Liczba zaraportowanych godzin utrzymania
    </th>
    <td class="text-right">
      <%= @invoice.entries.maintenance.sum(:hours) %>
    </td>
  </tr>
  <tr>
    <th class="text-right" colspan="2">
      Procent programowania
    </th>
    <td class="text-right">
      <%= number_to_percentage(@invoice.development_ratio * 100, precision: 0) %>
    </td>
  </tr>
  <tr>
    <th class="text-right" colspan="2">
      Procent utrzymania
    </th>
    <td class="text-right">
      <%= number_to_percentage(@invoice.maintenance_ratio * 100, precision: 0) %>
    </td>
  </tr>
</table>