config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :entries, only: [:index, :create, :update, :destroy] do
    collection do
      post :update_all
      delete :destroy_all
    end
  end
  resources :invoices, only: [:index, :show, :create, :edit, :update, :destroy]
  resources :projects, only: [:index, :create, :edit, :update, :destroy] do
    member do
      post :import
      put :upload
    end
  end

  root to: "entries#index"
end

app/views/shared/_flash.html.erb
<% flash.each do |type, message| %>
  <div class="alert alert-dismissible <%= bootstrap_class_for(type) %>" role="alert">
    <button class="close" data-dismiss="alert" aria-label="Zamknij">×</button>
    <%= message %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="bg-dark text-light flex-shrink-0">
  <div class="container py-3">
    <div class="d-flex justify-content-between">
      <div>
        &copy; 2020 <a href="https://kubakuzma.com" target="_blank" class="text-light">Kuba Kuźma</a>
      </div>
    </div>
  </div>
</footer>

app/views/shared/_navigation.html.erb
<nav class="navbar navbar-expand navbar-light bg-light">
  <div class="container px-3">
    <%= link_to "IPBOX.app", root_path, class: "navbar-brand" %>

    <% if signed_in? %>
      <ul class="navbar-nav">
        <li class="nav-item">
          <%= link_to "Projekty", projects_path, class: "nav-link #{'active' if controller_path.starts_with?('projects')}" %>
        </li>
        <li class="nav-item">
          <%= link_to "Faktury", invoices_path, class: "nav-link #{'active' if controller_path.starts_with?('invoices')}" %>
        </li>
        <li class="nav-item">
          <%= link_to "Wpisy", entries_path, class: "nav-link #{'active' if controller_path.starts_with?('entries')}" %>
        </li>
      </ul>
    <% end %>

    <ul class="navbar-nav ml-auto">
      <% if signed_in? %>
        <li class="nav-item">
          <%= link_to current_user.email, edit_user_registration_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Wyloguj się", destroy_user_session_path, data: {method: :delete}, class: "nav-link" %>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Zarejestruj się", new_user_registration_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</nav>