config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :entries, only: [:index, :create, :update, :destroy] do
    collection do
      post :update_all
      delete :destroy_all
    end
  end
  resources :invoices, only: [:index, :show, :create, :edit, :update, :destroy]
  resources :projects, only: [:index, :create, :edit, :update, :destroy] do
    member do
      post :import
      put :upload
    end
  end

  root to: "entries#index"
end

app/models/project.rb
class Project < ApplicationRecord
  has_many :entries, dependent: :destroy
  belongs_to :user
  has_one_attached :file

  enum default_type: {development: 1, maintenance: 2}

  validates :name, presence: true
  validates :default_type, presence: true
end

app/controllers/projects_controller.rb
# coding: utf-8
class ProjectsController < ApplicationController
  skip_before_action :verify_authenticity_token, only: [:import]
  skip_before_action :authenticate_user!, only: [:import]
  before_action :assign_user

  def index
    @projects = @user.projects.all
    @project = @user.projects.build
  end

  def create
    @project = @user.projects.build(project_params)
    if @project.save
      redirect_to edit_project_path(@project)
    end
  end

  def update
    @project = @user.projects.find(params[:id])
    if @project.update(project_params)
      redirect_to projects_path
    end
  end

  def edit
    @project = @user.projects.find(params[:id])
  end

  def import
    @project = Project.find_by(uuid: params[:id])

    if @project.entries.count > 0
      render body: "niepowodzenie: projekt zawiera wpisy\n"
    else
      ImportEntriesJob.perform_later(@project, CGI.unescape(request.raw_post))
      render body: "sukces: zaimportowano wpisy\n"
    end
  end

  def upload
    @project = @user.projects.find(params[:id])
    @project.update(file: params.dig(:project, :file))
    ImportCalendarJob.perform_later(@project)
    head :ok
  end

  def destroy
    @project = @user.projects.find(params[:id])
    @project.destroy
    redirect_to projects_path
  end

  private

  def assign_user
    @user = current_user
  end

  def project_params
    params.require(:project).permit(:name, :default_type)
  end
end

app/views/projects/_form.html.erb
<%= form_for project, html: {class: "modal", tabindex: -1, role: "dialog"}, data: {remote: true} do |form| %>
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">
          <% if form.object.new_record? %>
            Nowy projekt
          <% else %>
            Edytuj projekt
          <% end %>
        </h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true"><%= octicon "x" %></span>
        </button>
      </div>
      <div class="modal-body">
        <div class="form-group">
          <%= form.label :name, class: "form-label" %>
          <%= form.text_field :name, class: "form-control", autocomplete: "off" %>
          <%= bootstrap_invalid_feedback_for(form.object, :name) %>
        </div>

        <div class="form-group">
          <%= form.label :default_type, class: "form-label" %>
          <%= form.collection_select :default_type, Project.default_types.keys.map { |type| [type, t(type)] }, :first, :second, {prompt: true}, class: "form-control custom-select", autocomplete: "off" %>
          <small class="form-text text-muted">Wszystkie zaimportowane wpisy będą miały przypisany ten typ aktywności, będziesz mógł zmienić typ poszczególnych wpisów.</small>
          <%= bootstrap_invalid_feedback_for(form.object, :default_type) %>
        </div>
      </div>
      <div class="modal-footer">
        <%= link_to "Usuń", project_path(form.object), class: "btn btn-danger", data: {method: :delete, confirm: "Czy na pewno usunąć ten projekt?", remote: true} if form.object.persisted? %>
        <%= form.submit "Zapisz", class: "btn btn-primary" %>
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Anuluj</button>
      </div>
    </div>
  </div>
<% end %>

app/views/projects/_project.html.erb
<tr id="project-<%= project.id %>">
  <td>
    <%= link_to project.name, "javascript:void(0)", data: {toggle: "modal", target: "#edit_project_#{project.id}"} %>
    <span class="hover-only"><%= octicon "pencil" %></span>
  </td>
  <td class="text-center">
    <%= link_to project.entries.count, entries_path(q: {project_id_eq: project.id}) %>
    <span class="hover-only"><%= octicon "search" %></span>
  </td>
  <td class="text-center">
    <%= project.entries.sum(:hours) %>
  </td>
  <td class="text-right">
    <% if project.entries.empty? %>
      <%= link_to "Importuj wpisy", edit_project_path(project), class: "btn btn-warning btn-sm" %>
    <% end %>
  </td>
</tr>

app/views/projects/_table.html.erb
<%= render partial: "projects/form", collection: @projects, as: :project %>

<table class="table table-sm" id="projects">
  <thead>
    <tr>
      <th>
        Nazwa
        <span class="hover-only"><%= octicon "pencil" %></span>
      </th>
      <th class="text-center">
        Liczba wpisów
        <span class="hover-only"><%= octicon "pencil" %></span>
      </th>
      <th class="text-center">
        Liczba godzin
      </th>
      <th class="text-right"></th>
    </tr>
  </thead>
  <% if @projects.count > 0 %>
    <tbody>
      <%= render @projects %>
    </tbody>
  <% else %>
    <tr>
      <td colspan="3" class="text-center text-muted">Nie masz żadnych projektów</td>
    </tr>
  <% end %>
</table>

app/views/projects/create.js.erb
document.getElementById("new_project").innerHTML = "<%= j render('form', project: @project) %>";

app/views/projects/edit.html.erb
<div class="row my-3">
  <div class="col">
    <h2>
      Importuj wpisy
    </h2>
  </div>
</div>

<div class="my-3" data-controller="imports" data-imports-project-id="<%= @project.id %>">
  <div data-target="imports.awaiting">
    <p>
      Proszę wywołać następujące polecenie wewnątrz repozytorium
      importowanego projektu (cała linia jako jedno polecenie):
    </p>

    <p>
      <code>
git log --author <%= @user.email %> --no-merges --pretty="format:%H %aI %s" | curl -X POST <%= import_project_url(@project.uuid) %> --data-urlencode @-
      </code>
    </p>

    <p>
      W razie problemów z importem sprawdź, czy adres email którego
      użyłeś/użyłaś do rejestracji w serwisie pokrywa się z tym, którego
      używasz w Git.
    </p>

    <p class="my-3">
      lub
    </p>

    <%= form_for @project, url: upload_project_path(@project), html: {method: :put, remote: true} do |form| %>
      <div class="form-group">
        <%= form.label :file, "Załaduj kalendarz (zip)" %>
        <%= form.file_field :file, class: "form-control-file", accept: "application/zip", oninput: "Rails.fire(this.form, 'submit')" %>
      </div>
    <% end %>

    <p>
      Plik <em>ZIP</em> można wyeksportować z <a href="https://calendar.google.com/calendar/r/settings/export" target="_blank">Kalendarza Google</a> w <em>Menu Ustawienia</em>&nbsp;&rarr;&nbsp;<em>Importuj/Eksportuj</em>&nbsp;&rarr;&nbsp;<em>Eksportuj</em>.
    </p>

    <%= button_tag class: "btn btn-success", disabled: true do %>
      <span class="spinner-border spinner-border-sm" role="status"></span>
      Oczekiwanie na wpisy…
    <% end %>
  </div>

  <div data-target="imports.complete" class="d-none">
    <p>
      Pomyślnie zaimportowano <span data-target="imports.entries">0</span> wpisów.
    </p>
    <p>
      <%= link_to "Przeglądaj wpisy", entries_path(q: {project_id_eq: @project.id}), class: "btn btn-success" %>
    </p>
  </div>
</div>

app/views/projects/index.html.erb
<%= render "table" %>

<div class="text-right">
  <%= link_to "Dodaj projekt", "javascript:void(0)", class: "btn btn-success", data: {toggle: "modal", target: "#new_project"} %>
</div>

<%= render "form", project: @project %>